version: '3.7'

services:
  php:
    container_name: php-thenameofyourproject
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - XDEBUG_CONFIG=debug,coverage
    volumes:
      - .:/var/app
      - ~/.composer:/.composer
