version: '3.7'

services:
  php:
    container_name: php-dddfinitions
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - XDEBUG_MODE=coverage
    volumes:
      - .:/var/app
      - ~/.composer:/.composer
